# Generated by Django 2.2.9 on 2023-02-17 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
